### ISSUE TITLE
Not working AFK

### ISSUE THREAD

**Issue by Fmatteo91** [0wl/owls-tuners-recovery#3]
Hi! I don't know if it was meant to do this or if it's a problem I'm having, but it doesn't work AFK, it requires me to make a purchase in the clothing store in order to advance to the next level. Is it meant to be like this or am I doing something wrong?

**Comment by realrEDGUY** [comment]
You gain XP by standing AFK.
You shouldn't need to buy clothing, though it is the faster way of doing it.
You can also ask a friend to do the Head-To-Head boosting.

EDIT:
Make sure you are in the LS car meet

**Comment by 0wl** [comment]
In the game every **+- 4 Minutes** you get XP by standing AFK in the car meet area.

Here is an example video showing that you do indeed do get XP while being AFK: 
https://www.youtube.com/watch?v=wo3H3TFyzgA
