### ISSUE TITLE
Doesn't Work at all

### ISSUE THREAD

**Issue by RTH-Retribution** [0wl/owls-tuners-recovery#4]
Not sure if this is an issue with the script or just gta as a whole but as you can see by the title this doesnt seem to work, by not work I mean it literally does nothing when enabled. (trusted mode is on)

**Comment by realrEDGUY** [comment]
I'll look into it on sunday

**Comment by realrEDGUY** [comment]
Worked perfectly for me. Are you able to show me what is not working?

**Comment by RTH-Retribution** [comment]
> Worked perfectly for me. Are you able to show me what is not working?

I would've been but I recently managed to make it work by reinstalling gta v so it mustve been something wrong with my game.
